ml_params:
  train_split_ratio: 0.7
  val_split_ratio: 0.85
  target_col: ['target_yellow', 'target_green', 'target_hvfhv']

optuna_param_spaces: { 
  
  "lgbm": {
        "learning_rate": {'type': 'float', 'low': 0.01, 'high': 0.2, 'log': True},
        "num_leaves": {"type": "int", "low": 16, "high": 128},
        "max_depth": {"type": "int", "low": -1, "high": 12},
        "min_child_samples": {"type": "int", "low": 50, "high": 500},
        "subsample": {"type": "float", "low": 0.5, "high": 1.0},
        "colsample_bytree": {"type": "float", "low": 0.6, "high": 1.0},
        "reg_alpha": {"type": "float", "low": 1e-3, "high": 10, "log": True},
        "reg_lambda": {"type": "float", "low": 1e-3, "high": 10,"log": True},
      #  "min_split_gain": {"type": "float","low": 0.0,"high": 0.3},
    },

    "xgboost": {
        "learning_rate": {"type": "float", "low": 1e-2, "high": 0.2, "log": True},
        "max_depth": {"type": "int","low": 4, "high": 8},
        "min_child_weight": {"type": "float","low": 20, "high": 100},
        "subsample": {"type": "float", "low": 0.6, "high": 0.9},
        "colsample_bytree": {"type": "float","low": 0.6, "high": 1.0},
        "colsample_bylevel": {"type": "float","low": 0.6,"high": 1.0},
        "reg_alpha": {"type": "float","low": 1e-5,"high": 0.5,"log": True},
        "reg_lambda": {"type": "float", "low": 1e-2, "high": 10, "log": True},
        "gamma": {"type": "float","low": 1e-1, "high": 1.0, "log": True},
    },

    "catboost": {
        "learning_rate": {"type": "float","low": 1e-2, "high": 0.2,"log": True},
        "depth": {"type": "int","low": 4,"high": 8},
        "l2_leaf_reg": {"type": "float","low": 1.0, "high": 10.0},
        "bagging_temperature": {"type": "float","low": 0.0,"high": 1.0},
        "random_strength": {"type": "float", "low": 0.0,"high": 10.0},
        "border_count": {"type": "int", "low": 16, "high": 128},
       "min_data_in_leaf": {"type": "int","low": 16,"high": 64},
       "grow_policy": {"type": "categorical", "choices": ["SymmetricTree", "Depthwise", "Lossguide"]},
    },

  "random_forest": {
        "n_estimators": {"type": "int", "low": 100, "high": 150},
        "max_depth": {"type": "int", "low": 5, "high": 20},
        "min_samples_split": {"type": "int", "low": 2, "high": 20},
        "min_samples_leaf": {"type": "int", "low": 20, "high": 100},
        "max_features": {"type": "categorical", "choices": ["sqrt", "log2"]},
    },

  }